
function if_osx {
  if [ $(uname) = "Darwin" ]; then
    echo "$1"
  else
    echo "$2"
  fi
}

function haddock {
    stack haddock --open $1
}

#function man {
#    vim -c "SuperMan $*"
#
#    if [ "$?" != "0" ]; then
#        echo "No manual entry for $*"
#    fi
#}

# add bash functions
#source "${HOME}/gits/fresh-install/profile/profile.all"
#source "${HOME}/gits/fresh-install/profile/profile.$(if_osx "osx" "unix")"
#source "${HOME}/gits/fresh-install/profile/refresh.sh"
#source "${HOME}/gits/fresh-install/profile/cabal.sh"
source "${HOME}/gits/fresh-install/profile/git-prompt.sh"
#source "${HOME}/gits/fresh-install/profile/color.sh"
#source "${HOME}/gits/fresh-install/profile/theano-env.sh"

# add bash functions
source ${HOME}/gits/fresh-install/bash/color.sh
source ${HOME}/gits/fresh-install/bash/fresh-install.sh
source ${HOME}/gits/fresh-install/bash/platform.sh
source ${HOME}/gits/fresh-install/bash/ps1.sh

# add custom executables
export PATH=$PATH:$HOME/gits/haskell-sandbox/.cabal-sandbox/bin/
export PATH=$PATH:$HOME/gits/new-prelude/.cabal-sandbox/bin
export PATH=$PATH:$HOME/gits/microbreak/.cabal-sandbox/bin
export PATH=$PATH:$HOME/.local/bin

# add tmux functions
export PATH=$PATH:$HOME/gits/tmux/dev-tmux

# Added by Canopy installer on 2014-09-30
# VIRTUAL_ENV_DISABLE_PROMPT can be set to '' to make bashprompt show that Canopy is active, otherwise 1
VIRTUAL_ENV_DISABLE_PROMPT='' source ${HOME}/Library/Enthought/Canopy_64bit/User/bin/activate

