#!/bin/bash

export black=$(tput setaf 0)
export red=$(tput setaf 1)
export green=$(tput setaf 2)
export lime_yellow=$(tput setaf 190)
export yellow=$(tput setaf 3)
export powder_blue=$(tput setaf 153)
export blue=$(tput setaf 4)
export magenta=$(tput setaf 5)
export cyan=$(tput setaf 6)
export white=$(tput setaf 7)
export bright=$(tput bold)
export color_off=$(tput sgr0)
export blink=$(tput blink)
export reverse=$(tput smso)
export underline=$(tput smul)
